spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 619211091396-pc5ik8gqfmsg047ld407vmc14irvalhm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          kakao:
            client-id: a4777e04b7c3483aa16f9b46a5960d48
            client-secret: UZ3kKo8M7vhJWwfGWgRRmTm3l41kwgSx
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hojunara?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: seotj0413@gmail.com
    password: kdkv oezc jmvn bnbr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: hojulog
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAXYKJVHADTQ7VT35J
      secretKey: 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

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTczMDc2OTQ4NywiaWF0IjoxNzMwNzY5NDg3fQ.V0TwWaSCpgFfCbzz1n_4sZCouR1O9K5gujCcwh1-y8Q