package com.promo.web.entity;

public enum SubCategory {
    // Technology
    MOBILE_APPLICATION,
    WEB_APPLICATION,
    AI_APPLICATION,
    BLOCKCHAIN_APPLICATION,
    IOT_SOLUTIONS,
    CLOUD_COMPUTING_SERVICES,
    CYBERSECURITY_TOOLS,
    AR_VR_APPLICATIONS,
    DATA_ANALYTICS_PLATFORMS,
    E_COMMERCE_SOLUTIONS,
    DEVOPS_TOOLS,
    MACHINE_LEARNING_MODELS,
    GAME_DEVELOPMENT,
    SAAS_PLATFORMS,
    ROBOTICS_SOLUTIONS,
    THREE_D_PRINTING_SOLUTIONS,
    BIG_DATA_APPLICATIONS,
    NETWORKING_TOOLS,
    QUANTUM_COMPUTING_APPLICATIONS,
    DIGITAL_TWINS,
    TECHNOLOGY_ETC,

    // Restaurant
    ITALIAN,
    FRENCH,
    JAPANESE,
    CHINESE,
    INDIAN,
    MEXICAN,
    AMERICAN,
    KOREAN,
    THAI,
    SPANISH,
    FAST_FOOD,
    DESSERTS,
    CAFE,
    RESTAURANT_ETC,

    // Education
    ONLINE_COURSES,
    LEARNING_MANAGEMENT_SYSTEM,
    TUTORING_SERVICES,
    EDUCATION_ETC,

    // Lifestyle
    FITNESS_AND_WELLNESS,
    TRAVEL_AND_TOURISM,
    PERSONAL_FINANCE,
    LIFESTYLE_ETC,

    // Entertainment
    MOVIE,
    DRAMA,
    MUSIC,
    CONCERTS_AND_LIVE_EVENTS,
    VIDEO_STREAMING_SERVICES,
    STAND_UP_COMEDY,
    YOUTUBE_CHANNELS,
    MUSEUMS_AND_EXHIBITS,
    SPORTS_EVENTS,
    ART_EXHIBITIONS,
    ENTERTAINMENT_ETC;
}